import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, signInAnonymously } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getDatabase, ref, set, get, update, remove, onValue, onDisconnect, push, runTransaction, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js";
const firebaseConfig={"apiKey": "AIzaSyBhPwBFWgqeSfN8zSM4Pu6Dg-8suzeqHus", "authDomain": "versatil-sala-de-jogos.firebaseapp.com", "databaseURL": "https://versatil-sala-de-jogos-default-rtdb.firebaseio.com", "projectId": "versatil-sala-de-jogos", "storageBucket": "versatil-sala-de-jogos.firebasestorage.app", "messagingSenderId": "345907094201", "appId": "1:345907094201:web:ef4dff6b6084fecc197168"};
const fb=initializeApp(firebaseConfig), auth=getAuth(fb), db=getDatabase(fb);
const $=s=>document.querySelector(s); let uid=null,nick='',queueKey=null,roomId=null,unsub=null,room=null,botTimer=null,matching=false,botBusy=false;
const views=[$('#homeView'),$('#queueView'),$('#gameView')]; function show(v){views.forEach(x=>x.classList.add('hidden'));v.classList.remove('hidden')}
function clean(v){return ((v||'').trim().replace(/[.#$\[\]\/]/g,'').slice(0,18)||'Jogador')}
function randomNick(){let a=['Tucano','Lobo','Sol','Atlas','Brisa','Nuvem','Falcão','Luna','Rio','Orion'];return a[Math.floor(Math.random()*a.length)]+Math.floor(10+Math.random()*90)}
function win(b){for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'draw':''}
function mine(r){return r?.players?.X?.uid===uid?'X':r?.players?.O?.uid===uid?'O':''} function opp(r){return mine(r)==='X'?r.players.O:r.players.X}
async function boot(){try{$('#connBadge').textContent='Autenticando…';let c=await signInAnonymously(auth);uid=c.user.uid;let p=ref(db,'presence/'+uid);await set(p,{online:true,updatedAt:serverTimestamp()});onDisconnect(p).remove();$('#connBadge').textContent='Firebase online'}catch(e){console.error(e);$('#connBadge').textContent='Falha na conexão';alert('Falha ao conectar ao Firebase.')}}
async function join(){if(!uid||matching)return;matching=true;nick=clean($('#nick').value);$('#nick').value=nick;await set(ref(db,'players/'+uid),{nick,lastSeen:serverTimestamp()});show($('#queueView'));let q=push(ref(db,'queues/tictactoe'));queueKey=q.key;await set(q,{uid,nick,createdAt:Date.now(),status:'waiting'});onDisconnect(q).remove();seek();botTimer=setTimeout(()=>{if(matching&&!roomId)makeBot()},8000)}
async function seek(){if(!matching||roomId)return;let s=await get(ref(db,'queues/tictactoe'));let e=Object.entries(s.val()||{}).map(([key,v])=>({key,...v})).filter(x=>x.status==='waiting'&&x.uid!==uid).sort((a,b)=>a.createdAt-b.createdAt);if(!e.length)return setTimeout(seek,1000);let o=e[0], pair=[uid,o.uid].sort(), rid='ttt_'+pair.join('_'); if(uid!==pair[0])return setTimeout(checkRoom,500);let rr=ref(db,'rooms/'+rid);await runTransaction(rr,r=>r||{game:'tictactoe',status:'active',createdAt:Date.now(),players:{X:{uid,nick,type:'human'},O:{uid:o.uid,nick:o.nick||'Adversário',type:'human'}},board:['','','','','','','','',''],turn:'X',winner:'',rematch:{}});await Promise.allSettled([remove(ref(db,'queues/tictactoe/'+queueKey)),remove(ref(db,'queues/tictactoe/'+o.key))]);enter(rid)}
async function checkRoom(){if(!matching||roomId)return;let s=await get(ref(db,'rooms'));for(const [rid,r] of Object.entries(s.val()||{}))if(r?.status==='active'&&Object.values(r.players||{}).some(p=>p?.uid===uid))return enter(rid);setTimeout(seek,700)}
async function makeBot(){let rid='ttt_bot_'+uid+'_'+Date.now(),names=['Orion','Atlas','Luna','Nexus'];await set(ref(db,'rooms/'+rid),{game:'tictactoe',status:'active',createdAt:Date.now(),players:{X:{uid,nick,type:'human'},O:{uid:'bot',nick:names[Math.floor(Math.random()*names.length)],type:'bot'}},board:['','','','','','','','',''],turn:'X',winner:'',rematch:{}});if(queueKey)await remove(ref(db,'queues/tictactoe/'+queueKey));enter(rid)}
function enter(rid){roomId=rid;matching=false;clearTimeout(botTimer);show($('#gameView'));$('#matchInfo').textContent='Sala '+rid.slice(-10);if(unsub)unsub();unsub=onValue(ref(db,'rooms/'+rid),s=>{if(!s.exists())return;room=s.val();render();botMove()})}
function render(){let m=mine(room),o=opp(room),b=Array.isArray(room.board)?room.board:['','','','','','','','',''];$('#meBox').innerHTML='<strong>'+nick+' ('+m+')</strong><small>Você</small>';$('#oppBox').innerHTML='<strong>'+(o?.nick||'Adversário')+' ('+(m==='X'?'O':'X')+')</strong><small>'+(o?.type==='bot'?'Jogador virtual':'Jogador online')+'</small>';let el=$('#board');el.innerHTML='';b.forEach((v,i)=>{let bt=document.createElement('button');bt.className='cell';bt.textContent=v;bt.disabled=!!room.winner||room.turn!==m||!!v;bt.onclick=()=>move(i);el.appendChild(bt)});if(room.winner){let title=room.winner==='draw'?'Empate':room.winner===m?'Você venceu!':'Você perdeu!';$('#status').textContent=title;$('#endTitle').textContent=title;$('#endText').textContent=room.winner==='draw'?'A partida terminou empatada.':room.winner===m?'Boa partida.':'O adversário venceu esta rodada.';$('#endModal').classList.remove('hidden')}else $('#status').textContent=room.turn===m?'Sua vez':'Vez de '+(o?.nick||'adversário')}
async function move(i){await runTransaction(ref(db,'rooms/'+roomId),r=>{if(!r||r.winner)return r;let m=r.players.X.uid===uid?'X':r.players.O.uid===uid?'O':'';if(!m||r.turn!==m||r.board[i])return r;let b=[...r.board];b[i]=m;r.board=b;let w=win(b);if(w)r.winner=w;else r.turn=m==='X'?'O':'X';return r})}
function botPick(b,mark,human){let cells=b.map((v,i)=>v?null:i).filter(i=>i!==null);for(let i of cells){let x=[...b];x[i]=mark;if(win(x)===mark)return i}for(let i of cells){let x=[...b];x[i]=human;if(win(x)===human)return i}if(!b[4])return 4;return cells[Math.floor(Math.random()*cells.length)]}
function botMove(){if(botBusy||!room||room.winner)return;let side=room.players?.O?.type==='bot'?'O':'';if(!side||room.turn!==side)return;botBusy=true;setTimeout(async()=>{await runTransaction(ref(db,'rooms/'+roomId),r=>{if(!r||r.winner||r.turn!==side)return r;let b=[...r.board],i=botPick(b,side,'X');b[i]=side;r.board=b;let w=win(b);if(w)r.winner=w;else r.turn='X';return r});botBusy=false},900)}
async function rematch(){$('#endModal').classList.add('hidden');let o=opp(room);if(o?.type==='bot')return update(ref(db,'rooms/'+roomId),{board:['','','','','','','','',''],turn:'X',winner:'',rematch:{}});await set(ref(db,'rooms/'+roomId+'/rematch/'+uid),true);$('#status').textContent='Pedido de revanche enviado…';let s=await get(ref(db,'rooms/'+roomId+'/rematch')),v=s.val()||{},ids=Object.values(room.players).filter(p=>p.type==='human').map(p=>p.uid);if(ids.every(x=>v[x]))await update(ref(db,'rooms/'+roomId),{board:['','','','','','','','',''],turn:'X',winner:'',rematch:{}})}
async function back(){clearTimeout(botTimer);matching=false;if(queueKey)try{await remove(ref(db,'queues/tictactoe/'+queueKey))}catch{}queueKey=null;if(unsub){unsub();unsub=null}roomId=null;room=null;$('#endModal').classList.add('hidden');show($('#homeView'))}
$('#randomNick').onclick=()=>$('#nick').value=randomNick();$('#playTTT').onclick=join;$('#cancelQueue').onclick=back;$('#leaveGame').onclick=back;$('#backBtn').onclick=back;$('#rematchBtn').onclick=rematch;boot();